# Generated by Django 2.0.1 on 2018-01-03 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='director_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rating',
        ),
    ]
